version: '3'

services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:15.3.0
    container_name: piwigo
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Amsterdam
    volumes:
      - piwigo-images-config:/config
      - piwigo-images-gallery:/gallery
    restart: unless-stopped
    networks:
      - nginx
      - piwigo_internal_network

  piwigo-database:
    container_name: piwigo-database
    image: mariadb:11-ubi
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - piwigo_internal_network


volumes:
  piwigo-images-config:
  piwigo-images-gallery:

networks:
  piwigo_internal_network:
    name: piwigo_internal_network

  nginx:
    name: nginxproxymanager_default
    external: true